### ISSUE TITLE
[BUG] Click player head in the GUI and got console error

### ISSUE THREAD

**Issue by maxlehot1234** [BentoBoxWorld/Visit#1]
#### Describe the bug

I click the visit player head and than got this in the console:
https://gist.github.com/maxlehot1234/c544f28a60231258b9acf63f59229ed1

#### Steps to reproduce the behavior

Simply update bentobox to latest version and aoneblock  (for me) and visit addon and ./ob visit to open the GUI. Click on the player head and check the console

#### Expected behavior

When I click the player head in the GUI it should teleport me on the player island, no? :)
##### Output of `/bbox version` (Mandatory)

```
>.... [01:08:27 INFO]: Running PAPER 1.16.1.
>.... [01:08:27 INFO]: BentoBox version: 1.15.0-SNAPSHOT-b1847
>.... [01:08:27 INFO]: Database: JSON
>.... [01:08:27 INFO]: Loaded Game Worlds:
>.... [01:08:27 INFO]: oneblock_world (OneBlock): Overworld
>.... [01:08:27 INFO]: Loaded Addons:
>.... [01:08:27 INFO]: AOneBlock 1.4.1-SNAPSHOT-b124 (ENABLED)
>.... [01:08:27 INFO]: Border 1.0.9 (ENABLED)
>.... [01:08:27 INFO]: ControlPanel 1.13.0-SNAPSHOT-b41 (ENABLED)
>.... [01:08:27 INFO]: IslandFly 1.8.0 (ENABLED)
>.... [01:08:27 INFO]: Limits 1.15.0-SNAPSHOT-b227 (ENABLED)
>.... [01:08:27 INFO]: Upgrades 0.2.0-SNAPSHOT-b64 (ENABLED)
>.... [01:08:27 INFO]: Visit 1.0.0-ALPHA (ENABLED)
```

Thanks and have a nice day

**Comment by BONNe** [comment]
Fixed in the latest version.
