### ISSUE TITLE
Can't set visit location in v1.3.0

### ISSUE THREAD

**Issue by Jordancjb** [BentoBoxWorld/Visit#10]
#### Describe the bug
Whenever anybody tries /island visit setLocation
it says there is not a player names setLocation

#### Steps to reproduce the behavior
just run /island visit setLocation on bskyblock with the visit 1.3.0 addon

#### Expected behavior
it should set the location where players go when they visit you

#### Screenshots and videos (Optional)
none

### Environment
bskyblock running on TUINITY 1.16.5 with visit addon v1.3.0

##### Output of `/bbox version` (Mandatory)

```
Running Invalid (TUINITY) 1.16.5.
Database: JSON
BentoBox version: 1.16.0
Loaded Game Worlds:
Loaded Addons:
bskyblock_world (BSkyBlock): Overworld, Nether*
BSkyBlock 1.14.1-SNAPSHOT-b673 (ENABLED)
Visit 1.3.0 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by BONNe** [comment]
It is my fail (from one side)

BentoBox does not support capital letters in command aliases. You can fix it locally by changing "setLocation" to "setlocation".

**Comment by BONNe** [comment]
I created a bug report in BentoBox Repo:
https://github.com/BentoBoxWorld/BentoBox/issues/1706

I need to know the outcome of it before fixing it.

**Comment by Jordancjb** [comment]
well ill try changing it to see if that fixes it

Thank You for the quick reply!

**Comment by Jordancjb** [comment]
Hmm it seems when I change it to "setlocation" via the visit addon config it just doesn't do anything? like now nothing pops up in chat and it doesn't set the visit location

could I be doing something wrong?

**Comment by BONNe** [comment]
It may be true that I also forgot to add success message after changing location

**Comment by Jordancjb** [comment]
well when people visit me they don't go to the set location? I'm still not sure what's wrong and it could be my fault but i am gonna try 1.4.0 to see if that fixed anything?

Anyway thank you for helping so far!

edit: I tried it and yeah still the same issue of it not setting the location
I visited myself to test and it is just my islands original spawn location
