### ISSUE TITLE
Notification when a visitor enters the island

### ISSUE THREAD

**Issue by Razorxd1993** [BentoBoxWorld/Visit#20]
### Is your feature request related to a problem?

Is it possible to add that the island owner receives a notification when a visitor enters his island ?

Kind regards

### Describe the solution you'd like.

Is it possible to add that the island owner receives a notification when a visitor enters his island ?

Kind regards

### Describe alternatives you've considered.

No alternative

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
I have a question:
Should it be as a FLAG (owners can toggle to receive or not receive the message) or it should be just an admin setting where the admin can toggle it on/off?

**Comment by Razorxd1993** [comment]
As Flag
