### ISSUE TITLE
Discovered a small translation issue

### ISSUE THREAD

**Issue by BBDL233** [BentoBoxWorld/Visit#31]
### Expected behavior

The correct one should be like this
![image](https://github.com/BentoBoxWorld/Visit/assets/99265367/ee877968-3a71-4c48-9d53-eaa43e320f9d)

### Observed/Actual behavior

But in reality, it's like this
![image](https://github.com/BentoBoxWorld/Visit/assets/99265367/8dcf5338-00a0-4399-b3ed-14db952c51dc)

### Steps/models to reproduce

Place the addon jar in the addons folder of the BentoBox plugin
Restart the server

### BentoBox version

服务器： PAPER 1.20.4
BentoBox 版本： 2.0.0
数据库： MYSQL
已载入的游戏世界：
oneblock_world (OneBlock) : 主世界, 下界, 末地*
已载入的附加组件：
AOneBlock 1.15.0 (ENABLED)
Visit 1.6.0 (ENABLED)
---
Run /bbox version on your server and paste the full, unmodified output here.
"latest" is not a version; we require the output of /bbox version so we can adequately track down the issue.
Additionally, do NOT provide a screenshot, you MUST paste the entire output.

but the server lang is chinese 

### Plugin list

Bukkit Plugins:
 - AdvancedChat, AlonsoLevels, AureliumSkills, BentoBox, BentoBox-AOneBlock, BentoBox-Visit, ChatGames, ChestCommands, DecentHolograms, InfiniteScoreboard JSEngine, LuckPerms, momojs, Multiverse-Core, NBTAPI, PlaceholderAPI, ProtocolLib, RewardsLite, TAB, UltraEconomy Vault, ViaBackwards, ViaRewind, ViaVersion, WorldBorderAPI

### Other

It's actually quite simple. There was a problem with the language files produced automatically
I have already made the necessary modifications
![image](https://github.com/BentoBoxWorld/Visit/assets/99265367/01ea5aa7-659f-42ef-a8b7-f426e80e6c23)
Just add this information here to display it normally

**Comment by BBDL233** [comment]
No, it should be like this
![image](https://github.com/BentoBoxWorld/Visit/assets/99265367/afeba1e2-d2e0-4e82-9667-a920359831c1)

**Comment by tastybento** [comment]
Can you copy and paste the Chinese here please? I cannot read it from the graphic.

**Comment by BBDL233** [comment]
[BentoBox_locales_Visit_zh-CN.zip](https://github.com/BentoBoxWorld/Visit/files/14268434/BentoBox_locales_Visit_zh-CN.zip)

**Comment by BBDL233** [comment]
This is the correct configuration file

**Comment by tastybento** [comment]
Thanks!
