### ISSUE TITLE
Customizable Back/Next Button

### ISSUE THREAD

**Issue by Fredthedoggy** [BentoBoxWorld/Visit#8]
#### Is your feature request related to a problem?

Nope

#### Describe the solution you'd like us to implement.

Allow for user's to change the item used for going forward/backwards in the GUI. Currently it is only a pink-tipped arrow.

#### Describe alternatives you've considered.

None

### Additional context

Discussed on discord

**Comment by BONNe** [comment]
This will be implemented if and when BentoBox will have customizable GUIs.

Currently will not bother to do it :D
