### ISSUE TITLE
Auto payment can be abuse

### ISSUE THREAD

**Issue by Tanerx** [BentoBoxWorld/Visit#9]
#### Is your feature request related to a problem?

Yes

#### Describe the solution you'd like us to implement.

When visit a island and island have Payment, money auto removing from user. (when using "/is visit player" )
Show user to this island have payment visit and how much. Do not teleport/take money from user until confirmation.
Ask confirmation even using just visit gui or command.

### Additional context

Server admin can set Max payment island owners can set. 
Server admin can set disable payment.

**Comment by FinlayHDev** [comment]
This would be a really useful feature to get implemented.

**Comment by BONNe** [comment]
it is implemented in latest dev version.
